// Auto-generated by parallel_unsplash_photos_search
// Do not edit manually

export const IMAGES = {
  ANALYTICS_1: "https://images.unsplash.com/photo-1608222351212-18fe0ec7b13b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMGFuYWx5dGljcyUyMGRhc2hib2FyZHxlbnwwfDB8fHwxNzczNTQ2OTM3fDA&ixlib=rb-4.1.0&q=80&w=1080",
  ANALYTICS_2: "https://images.unsplash.com/photo-1748609160056-7b95f30041f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwyfHxidXNpbmVzcyUyMGFuYWx5dGljcyUyMGRhc2hib2FyZHxlbnwwfDB8fHwxNzczNTQ2OTM3fDA&ixlib=rb-4.1.0&q=80&w=1080",
  ANALYTICS_3: "https://images.unsplash.com/photo-1758876202980-0a28b744fb24?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw3fHxidXNpbmVzcyUyMGFuYWx5dGljcyUyMGRhc2hib2FyZHxlbnwwfDB8fHwxNzczNTQ2OTM3fDA&ixlib=rb-4.1.0&q=80&w=1080",
  ANALYTICS_4: "https://images.unsplash.com/photo-1748609278627-4b0e483b9b70?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw0fHxidXNpbmVzcyUyMGFuYWx5dGljcyUyMGRhc2hib2FyZHxlbnwwfDB8fHwxNzczNTQ2OTM3fDA&ixlib=rb-4.1.0&q=80&w=1080",
  ANALYTICS_5: "https://images.unsplash.com/photo-1763038311036-6d18805537e5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw2fHxidXNpbmVzcyUyMGFuYWx5dGljcyUyMGRhc2hib2FyZHxlbnwwfDB8fHwxNzczNTQ2OTM3fDA&ixlib=rb-4.1.0&q=80&w=1080",
  ANALYTICS_6: "https://images.unsplash.com/photo-1759661966728-4a02e3c6ed91?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwzfHxidXNpbmVzcyUyMGFuYWx5dGljcyUyMGRhc2hib2FyZHxlbnwwfDB8fHwxNzczNTQ2OTM3fDA&ixlib=rb-4.1.0&q=80&w=1080",
  ANALYTICS_7: "https://images.unsplash.com/photo-1759752394755-1241472b589d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw1fHxidXNpbmVzcyUyMGFuYWx5dGljcyUyMGRhc2hib2FyZHxlbnwwfDB8fHwxNzczNTQ2OTM3fDA&ixlib=rb-4.1.0&q=80&w=1080",
  ANALYTICS_8: "https://images.unsplash.com/photo-1763718528755-4bca23f82ac3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw4fHxidXNpbmVzcyUyMGFuYWx5dGljcyUyMGRhc2hib2FyZHxlbnwwfDB8fHwxNzczNTQ2OTM3fDA&ixlib=rb-4.1.0&q=80&w=1080",
} as const;

export type ImageKey = keyof typeof IMAGES;
